const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],
    safelist: [
        'w-[83px]',
        'h-[101px]',
        'w-[116px]',
        'h-[24px]',
        'w-[142px]',
        'h-[27px]',
        'w-[33.68px]',
        // 'h-[19.24px]',
        'w-[38.01px]',
        'h-[21.72px]',
        'w-[12.38px]',
        'h-[12.38px]',
        'w-[56.68px]',
        'h-[56.68px]',
        'w-[50.38px]',
        'h-[50.38px]',
        'w-[50px]',
        'h-[50px]',
        'w-[363px]',
        'h-[287px]',
        'w-[398px]',
        'h-[636px]',
        'w-[58.79px]',
        'h-[12.53px]',
        'w-[34px]',
        'h-[34px]',
        'w-[19.24px]',
        'h-[19.24px]',
        'w-[867px]',
        'h-[613px]',
        'w-[838px]',
        'h-[418.63px]',
        'w-[142px]',
        'h-[27px]',
        'w-[90px]',
        'h-[110.42px]',
        'w-[1098px]',
        'h-[56.86px]',
        'w-[56.86px]',
        'h-[393px]',
        'w-[557px]',
        'h-[357px]',
        'w-[93.54px]',
        'h-[114.21px]',
        'w-[340px]',
        'h-[450px]',
        'w-[120px]',
        'h-[35px]',
        'w-[160px]',
        'h-[40px]',
        'w-[27.17px]',
        'h-[15.52px]',
        'w-[317.28px]',
        'h-[244.42px]',
        'mt-[9.64px]',
        'mb-[3.05px]',
        'mx-[13px]',
        'top-[64px]',
        'top-[55px]',
        'ml-[35px]',
        'ml-[0px]',
        'text-[11px]',
        'text-[8.87px]',
        'rounded-[15px]',
        'rounded-[19.03px]',
      ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
            keyframes: {
                wiggle: {
                    '0%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-5px)' },
                    '100%': { transform: 'translateY(0px)' },
                }
              },
              animation: {
                wiggle: 'wiggle 0.5s ease-in-out forwards',
              }
        },
    },

    plugins: [require('@tailwindcss/forms')],
};
